addSbtPlugin("com.typesafe.sbt"   %  "sbt-native-packager"   % "1.1.6")
addSbtPlugin("com.typesafe.sbt"   %  "sbt-site"              % "1.2.0")
addSbtPlugin("net.virtual-void"   %  "sbt-dependency-graph"  % "0.7.5")
addSbtPlugin("org.scalariform"    %  "sbt-scalariform"       % "1.6.0")
addSbtPlugin("org.scoverage"      %  "sbt-scoverage"         % "1.3.5")
addSbtPlugin("org.scalastyle"     %% "scalastyle-sbt-plugin" % "0.8.0")
addSbtPlugin("org.tpolecat"       %  "tut-plugin"            % "0.5.1")
