addSbtPlugin("com.typesafe.sbt"   % "sbt-native-packager"  % "1.0.4")
addSbtPlugin("net.virtual-void"   % "sbt-dependency-graph" % "0.7.5")
addSbtPlugin("org.scalariform"    % "sbt-scalariform"      % "1.5.1")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"        % "1.3.3")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"              % "0.2.4")
